spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: mysecretpassword
    jpa:
        hibernate:
            ddl-auto: create-only
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    ai:
        azure:
            openai:
                endpoint: https://api.openai.com/v1
        openai:
            api-key: dummy
#        mcp:
#            client:
#                sse:
#                    connections:
#                        server1:
#                            url: http://localhost:8081
#                type: sync
#                request-timeout: 60s
#    datasource:
#        hikari:
#            connectionTimeout: 20000
#            maximumPoolSize: 5
#        password: mysecretpassword
#        url: jdbc:postgresql://localhost:5432/postgres
#        username: postgres
#    jpa:
#        hibernate:
#            ddl-auto: create-drop
#    neo4j:
#        authentication:
#            password: secretpass
#            username: neo4j
#        uri: bolt://localhost:7687

logging:
  level:
      org.springframework.ai.chat.client.advisor: DEBUG